### PR TITLE
Many of the header files contained an absolute path to Eigen. I have fix...

### PR DESCRIPTION
**Pull request by KentonMurray**
...ed that here so that it only relies on the Makefile. Already, the code had <Eigen/Sparse> in some places, but it always had <../3rdParty/Eigen/Dense>

### CODE REVIEW

**Comment by rsennrich** [comment]
this goes back to commit 233de0. Hieu, is there a use case where changing the Makefile wasn't enough?

**Comment by hieuhoang** [comment]
there was some confusion about whether we had to put the Eigen lib into the system directory or not, and if not, where would it go. My change was just to force some consistency.

But i think things have settled down and it's become clear that setting $EIGEN is sufficient. 

i think you should pull it.

**Comment by KentonMurray** [comment]
Just using $EIGEN works on my system and I think it is sufficient in general. This makes for an easier install in some environments (i.e. the cluster I am using where Eigen is a different directory).

**Comment by hieuhoang** [comment]
ah, now doesn't compile with moses 'cos moses doesn't know where Eigen is. We have to add another bjam flag, or insist that Eigen is in 3rdparty

**Pull request merged**
